/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_design;

import chatbot.Client.Client;
import java.net.SocketException;
import java.util.HashMap;
import java.util.List;

import javax.swing.*;
import java.util.Map;

/**
 * @author tldlir001
 */
public class GUI extends javax.swing.JFrame
{

    public Map<Integer, String> knownClients;
    public Map<Integer, String> knownGroups;

    private Client client;
    private static String name;

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
        this.setTitle(name);
        client = new Client(name, this);
        client.startListening();
        knownClients = new HashMap<>();
        knownGroups = new HashMap<>();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent)
            {
                if (JOptionPane.showConfirmDialog(rootPane,
                        "Are you sure you would like to leave the chat app?\nyour temporary identity will be lost", "Really Closing?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
                {
                    client.closeClient();
                    System.exit(0);
                }
            }
        });
    }

    //todo dont add own client
    public void addClient(int ID, String name)
    {
        if (client.id != ID)
        {
            knownClients.put(ID, name);
        }
        updateList();
    }

    public void updateList()
    {
        DefaultListModel<String> dlm = new DefaultListModel<>();
        for (int id : knownClients.keySet())
        {
            dlm.addElement(id + ":" + knownClients.get(id));
        }
        list_members.setModel(dlm);

        dlm = new DefaultListModel<>();
        for (int id : knownGroups.keySet())
        {
            dlm.addElement(id + ":" + knownGroups.get(id));
        }
        list_groups.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_members = new javax.swing.JList<>();
        btn_group = new javax.swing.JButton();
        lbl_grpmem = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_groups = new javax.swing.JList<>();
        lbl_actgrp = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btnBroadcast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_members.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                list_membersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_members);

        btn_group.setText("Create Group");
        btn_group.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_groupActionPerformed(evt);
            }
        });

        lbl_grpmem.setText("Online members");

        list_groups.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                list_groupsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(list_groups);

        lbl_actgrp.setText("Active Groups:");

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_refreshActionPerformed(evt);
            }
        });

        btnBroadcast.setText("Send to all");
        btnBroadcast.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBroadcastActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btn_group, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbl_grpmem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbl_actgrp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btn_refresh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnBroadcast, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_group, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lbl_grpmem, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btn_refresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBroadcast)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lbl_actgrp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_grpmem)
                    .addComponent(lbl_actgrp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_group)
                    .addComponent(btn_refresh)
                    .addComponent(btnBroadcast))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        updateList();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_groupActionPerformed
        String groupName = JOptionPane.showInputDialog("Enter group name");
        if (groupName == null || groupName.isEmpty())
        {
            return;
        }

        List<String> groupMembers = list_members.getSelectedValuesList();
        String message = "";
        for (String groupMember : groupMembers)
        {
            // Just need user ID
            message += groupMember.split(":")[0] + ":";
        }
        message += client.id;

        client.sendToServer("ginfo:-1:" + groupName, message);
    }//GEN-LAST:event_btn_groupActionPerformed

    long lastClicked = 0;
    static int doubleClickTime = 260;
    private void list_membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_membersMouseClicked
        if (System.currentTimeMillis() - lastClicked < doubleClickTime)
        {
            try
            {
                int otherID = (Integer.parseInt(list_members.getSelectedValue().split(":")[0]));
                ChatRoom chat = new ChatRoom(client, otherID, false);
                chat.setVisible(true);
                chat.setTitle(knownClients.get(otherID));
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Did not select user");
            }
        }
        lastClicked = System.currentTimeMillis();
    }//GEN-LAST:event_list_membersMouseClicked

    private void list_groupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_groupsMouseClicked
        if (System.currentTimeMillis() - lastClicked < doubleClickTime)
        {
            String selectedGroup = list_groups.getSelectedValue();
            if (selectedGroup == null)
            {
                return;
            }
            int groupID = Integer.parseInt(selectedGroup.split(":")[0]);
            client.addGroupChatRoom(groupID, selectedGroup.split(":")[1]);
        }
        lastClicked = System.currentTimeMillis();    }//GEN-LAST:event_list_groupsMouseClicked

    private void btnBroadcastActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBroadcastActionPerformed
    {//GEN-HEADEREND:event_btnBroadcastActionPerformed
        String message = JOptionPane.showInputDialog("Input your broadcast");
        client.sendToServer("amessage:" + client.id + ":", message);
    }//GEN-LAST:event_btnBroadcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        name = JOptionPane.showInputDialog("Enter name");
        if (name == null || name.isEmpty())
        {
            return; // if pressed cancel or close
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBroadcast;
    private javax.swing.JButton btn_group;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_actgrp;
    private javax.swing.JLabel lbl_grpmem;
    private javax.swing.JList<String> list_groups;
    private javax.swing.JList<String> list_members;
    // End of variables declaration//GEN-END:variables
}
